[build]
  command = "npm run build"
  publish = "/dist"
  functions = "functions"
  
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/solutions"
to = "/solutions/index.html"
status = 200
