[build]
  command = "npm run build"

[start]
  command = "npm run start"


[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[redirects]]
from = "/deeplinks"
to = "/deeplinks/index.html"
status = 200
