[build]
  command = "npm run build"
  publish = "/dist"
  functions = "functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/_redirects"
  to = "/_redirects"
  status = 200
